#!/usr/bin/env bash
# Integrate mkosi for reproducible, declarative Windows image builds.
#
# mkosi (systemd project) wraps dnf/apt/pacman to produce customised disk
# images with GPT partitioning, UKIs, dm-verity, and Secure Boot signing.
# IWT uses it as an optional backend for build-image.sh when
# IWT_IMAGE_BUILDER=mkosi is set.
#
# Usage:
#   setup-mkosi.sh [options]
#
# Options:
#   --check           Check mkosi availability only
#   --install         Install mkosi via pip/pipx
#   --generate        Generate a mkosi.conf for the current IWT config
#   --build           Build a Windows image using mkosi
#   --output PATH     Output image path (default: $IWT_IMAGE_DIR/windows.raw)
#   --winiso PATH     Path to Windows installation ISO
#   --inject-winbtrfs Inject WinBtrfs driver into the image
#   --sign-sb         Sign the image for Secure Boot (requires sbsign)
#   --help            Show this help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IWT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$IWT_ROOT/cli/lib.sh"
load_config

CHECK_ONLY=false
DO_INSTALL=false
DO_GENERATE=false
DO_BUILD=false
OUTPUT_PATH="${IWT_IMAGE_DIR:-/var/lib/iwt/images}/windows.raw"
WIN_ISO=""
INJECT_WINBTRFS="${IWT_INJECT_WINBTRFS:-false}"
SIGN_SB=false
MKOSI_CONF_DIR="${IWT_IMAGE_DIR:-/var/lib/iwt/images}/mkosi"

# --- Argument parsing ---

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check)            CHECK_ONLY=true; shift ;;
        --install)          DO_INSTALL=true; shift ;;
        --generate)         DO_GENERATE=true; shift ;;
        --build)            DO_BUILD=true; shift ;;
        --output)           OUTPUT_PATH="$2"; shift 2 ;;
        --winiso)           WIN_ISO="$2"; shift 2 ;;
        --inject-winbtrfs)  INJECT_WINBTRFS=true; shift ;;
        --sign-sb)          SIGN_SB=true; shift ;;
        --help|-h)
            sed -n '/^# Usage:/,/^[^#]/p' "$0" | grep '^#' | sed 's/^# \?//'
            exit 0
            ;;
        *) die "Unknown option: $1" ;;
    esac
done

[[ "$CHECK_ONLY" == false && "$DO_INSTALL" == false && \
   "$DO_GENERATE" == false && "$DO_BUILD" == false ]] && CHECK_ONLY=true

# --- Helpers ---

check_mkosi() {
    if command -v mkosi &>/dev/null; then
        local ver
        ver=$(mkosi --version 2>/dev/null | head -1 || echo "unknown")
        ok "mkosi found: $ver"
        return 0
    else
        err "mkosi not found"
        return 1
    fi
}

install_mkosi() {
    info "Installing mkosi..."
    if command -v pipx &>/dev/null; then
        pipx install mkosi
    elif command -v pip3 &>/dev/null; then
        pip3 install --user mkosi
    elif command -v apt-get &>/dev/null; then
        sudo apt-get install -y mkosi
    else
        die "Cannot install mkosi: no pipx, pip3, or apt-get found"
    fi
    ok "mkosi installed"
}

# --- Generate mkosi.conf ---

generate_mkosi_conf() {
    info "Generating mkosi configuration in $MKOSI_CONF_DIR..."
    mkdir -p "$MKOSI_CONF_DIR"

    # Determine Secure Boot key paths
    local sb_key="" sb_cert=""
    if [[ "$SIGN_SB" == true ]]; then
        sb_key="${IWT_SB_KEY:-/etc/iwt/secure-boot/db.key}"
        sb_cert="${IWT_SB_CERT:-/etc/iwt/secure-boot/db.crt}"
        [[ -f "$sb_key" ]]  || warn "Secure Boot key not found: $sb_key"
        [[ -f "$sb_cert" ]] || warn "Secure Boot cert not found: $sb_cert"
    fi

    cat > "$MKOSI_CONF_DIR/mkosi.conf" <<EOF
# IWT-generated mkosi configuration
# Generated by setup-mkosi.sh — edit to customise

[Distribution]
Distribution=windows

[Output]
Format=disk
Output=${OUTPUT_PATH}
OutputDirectory=$(dirname "$OUTPUT_PATH")
CompressOutput=no

[Partitions]
# EFI System Partition (FAT32, 512 MiB)
EspSize=512M
# Root partition (NTFS, remainder)
RootSize=

[Validation]
$(if [[ "$SIGN_SB" == true && -f "$sb_key" ]]; then
    echo "SecureBootKey=${sb_key}"
    echo "SecureBootCertificate=${sb_cert}"
fi)

[Host]
# Extra packages to install into the build environment
BuildPackages=
$(if [[ "$INJECT_WINBTRFS" == true ]]; then
    echo "# WinBtrfs driver will be injected via manage-drivers.sh"
fi)
EOF

    # Generate a mkosi.build script for driver injection
    if [[ "$INJECT_WINBTRFS" == true ]]; then
        cat > "$MKOSI_CONF_DIR/mkosi.build" <<'BUILDEOF'
#!/usr/bin/env bash
# mkosi build script — inject WinBtrfs driver into the image
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IWT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
"$IWT_ROOT/image-pipeline/scripts/manage-drivers.sh" winbtrfs inject \
    --image "$BUILDROOT"
BUILDEOF
        chmod +x "$MKOSI_CONF_DIR/mkosi.build"
    fi

    ok "mkosi.conf written to $MKOSI_CONF_DIR/mkosi.conf"
}

# --- Build ---

build_with_mkosi() {
    check_mkosi || die "mkosi is required for --build"
    [[ -f "$MKOSI_CONF_DIR/mkosi.conf" ]] || generate_mkosi_conf

    info "Building Windows image with mkosi..."
    info "  Config: $MKOSI_CONF_DIR/mkosi.conf"
    info "  Output: $OUTPUT_PATH"

    local mkosi_args=("--directory=$MKOSI_CONF_DIR")
    [[ -n "$WIN_ISO" ]] && mkosi_args+=("--source=$WIN_ISO")

    mkosi "${mkosi_args[@]}" build

    if [[ -f "$OUTPUT_PATH" ]]; then
        ok "Image built: $OUTPUT_PATH"
        local size
        size=$(du -sh "$OUTPUT_PATH" | cut -f1)
        info "  Size: $size"
    else
        die "mkosi completed but output not found: $OUTPUT_PATH"
    fi
}

# --- Main ---

if [[ "$DO_INSTALL" == true ]]; then
    install_mkosi
fi

if [[ "$CHECK_ONLY" == true ]]; then
    check_mkosi || suggest_install mkosi
    exit 0
fi

if [[ "$DO_GENERATE" == true ]]; then
    generate_mkosi_conf
fi

if [[ "$DO_BUILD" == true ]]; then
    build_with_mkosi
fi
